repos:
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black-jupyter

- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
  - id: isort

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.16.1'
  hooks:
  - id: mypy

- repo: https://github.com/dxa4481/truffleHog.git
  rev: v3.89.2
  hooks:
  - id: trufflehog
