name: Pull request workflow
run-name: ${{ github.actor }} is running the pull request workflow
on:
  pull_request:
    branches:    
      - main
  workflow_dispatch:
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'
      - name: Run pre-commit
        run: |
          pip install pre-commit
          pre-commit install
          pre-commit run --all-files